Change log for June 21, 2024 Vulkan SC 1.0.15 spec update:
  * update release number to 15 for this update and reflow spec language

Public issues:

  * None

Internal issues:

  * Merge VK 1.3.274 tag to sc_main (!362)
  * Merge 2024 copyright fixes to sc_main (!365)
  * Update memory reservation common validity to support extension object
    types (!363)
  * Merge VK 1.3.278 tag to sc_main (!369)
  * Make pipeline cache data alignment requirements
    implementation-specific (#212/!366)
  * Include shader module VUs for completeness (#214/!368)
  * Merge VK 1.3.281 tag to sc_main (!370)
  * Add extension processing script (!367)
  * Enable winrt acquire display extension for Vulkan SC (!372)
  * Merge VK 1.3.286 tag to sc_main (!375)
  * Record new Vulkan SC ratified extensions (!376)
  * Various fixes for auto-generated vulkan_json_parser.hpp (!374)

New Extensions:

  * VK_NV_acquire_winrt_display (!372)
  * VK_KHR_calibrated_timestamps (replaces VK_EXT_calibrated_timestamps)
  * VK_KHR_global_priority (replaces VK_EXT_global_priority)
  * VK_KHR_vertex_attribute_divisor (replaces VK_EXT_vertex_attribute_divisor)
  * VK_KHR_index_type_uint8
  * VK_KHR_line_rasterization

diff --git a/testBuild b/testBuild
--- a/testBuild
+++ b/testBuild
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 #
-# Copyright 2023 The Khronos Group Inc.
+# Copyright 2023-2024 The Khronos Group Inc.
 #
 # SPDX-License-Identifier: Apache-2.0
 
@@ -8,6 +8,9 @@
 # that is found under build_tests.
 
 # Usage: testBuild
+
+# Fail if any command fails
+set -e
 
 # Build the test spec in various configurations:
 function build_spec() {
@@ -22,6 +25,13 @@ function build_spec() {
 
   # Note: let options expand, do not quote
   ./makeSpec -spec $options -genpath build_tests/gen-$build -test html
+
+  # Only retain the <body> of the html, so most changes due to asciidoctor changes are not reflected
+  # in the test output.  The primary reason for the build tests is to exercise the asciidoctor
+  # extensions.
+  keepbody='BEGIN { in_body=0 } /<body/ { in_body=1 } /<\/body/ { in_body=0; print} { if (in_body) { print } }'
+  htmlpath=build_tests/gen-$build/out/html/
+  awk "$keepbody" < $htmlpath/vkspec.html > $htmlpath/vkspec-body.html
 }
 
 # Core:
@@ -50,7 +60,7 @@ echo "======================="
 result=0
 for build in core core-1.0 hic hic-1.0 copy2-1.0 all all-1.0; do
   echo "Verifying gen-$build is as expected..."
-  if ! diff build_tests/expectations/$build.html build_tests/gen-$build/out/html/vkspec.html; then
+  if ! diff build_tests/expectations/$build.html build_tests/gen-$build/out/html/vkspec-body.html; then
     echo "  FAILED"
     result=1
   fi
